server:
  port: 2922

qiniu:
  accessKey: #七牛云个人中心密匙 AccessKey
  secretKey: #七牛云个人中心密匙 SecretKey
  bucket: #存储空间名
  path: #访问的域名

spring:
  thymeleaf:
    suffix: .html
    encoding: UTF-8
    prefix: classpath:/templates/
    cache: false
    mode: LEGACYHTML5